#!name=番茄小说广告屏蔽去短剧
#!desc=番茄小说广告屏蔽（批量检查后已修正，低误杀），version = 0.1

[Rule]
# 原始规则
DOMAIN,p6-ad-sign.byteimg.com,REJECT
DOMAIN,p9-ad-sign.byteimg.com,REJECT
DOMAIN,i.snssdk.com,REJECT
DOMAIN,i-lq.snssdk.com,REJECT
DOMAIN,dig.bdurl.net,REJECT
DOMAIN,activity-ag.awemeughun.com,REJECT
DOMAIN,mcs.snssdk.com,REJECT
DOMAIN,tnc3-alisc1.snssdk.com,REJECT
DOMAIN,security-lq.snssdk.com,REJECT
DOMAIN,tnc3-aliec2.snssdk.com,REJECT
DOMAIN,is.snssdk.com,REJECT
DOMAIN,msync-im1-vip6-std.easemob.com,REJECT
DOMAIN,apd-pcdnwxlogin.teg.tencent-cloud.net,REJECT
DOMAIN,api.iegadp.qq.com,REJECT
DOMAIN,sf3-ttcdn-tos.pstatp.com,REJECT
DOMAIN-SUFFIX,pglstatp-toutiao.com,REJECT
DOMAIN,zijieapi,REJECT
DOMAIN,*default.ixigua.com,REJECT
DOMAIN,v6-novelapp.ixigua.com,REJECT
DOMAIN,*novelapp.ixigua.com,REJECT
DOMAIN-SUFFIX,byteorge.com,REJECT
DOMAIN-SUFFIX,bytegoofy.com,REJECT
DOMAIN-SUFFIX,bytedance.com,REJECT
DOMAIN,lf*-webcast-cdn-tos-ncdn.bytegecko.com
DOMAIN,bsync3-normal-hl.zijieapi.com,REJECT
DOMAIN,p*.douyinpic.com,REJECT
DOMAIN,ecombdimg.com,REJECT
DOMAIN,mon*-misc-*.fqnovel.com,REJECT


# 新增短剧广告规则（批量检查已修正）
DOMAIN-SUFFIX,webcast-cdn-tos-ncdn.bytegecko.com,REJECT
DOMAIN,bsync3-normal-hl.zijieapi.com,REJECT
DOMAIN-SUFFIX,douyinpic.com,REJECT
DOMAIN,ecombdimg.com,REJECT
URL-REGEX,^https?:\/\/mon.*-misc-.*\.fqnovel\.com,REJECT

# IP拦截
IP-CIDR,49.71.37.101/32,REJECT,no-resolve
IP-CIDR,117.71.105.23/32,REJECT,no-resolve
IP-CIDR,218.94.207.205/32,REJECT,no-resolve
IP-CIDR,117.92.229.188/32,REJECT,no-resolve
IP-CIDR,101.36.166.16/32,REJECT,no-resolve
IP-CIDR,180.96.2.114/32,REJECT,no-resolve

# 正则拦截
URL-REGEX,*-default.ixigua.com,REJECT
URL-REGEX,^http:\/\/.+\.byteimg\.com\/ad-app-package,REJECT
URL-REGEX,^http:\/\/.+\.byteimg\.com\/web\.business\.image,REJECT

[URL Rewrite]
^https?:\/\/.+\.pangolin-sdk-toutiao\.com\/api\/ad\/union\/sdk\/(get_ads|stats|settings)\/ _ reject
^https?:\/\/.+\.pglstatp-toutiao\.com\/.+\/toutiao\.mp4 _ reject
^https?:\/\/.+\.(pglstatp-toutiao|pstatp)\.com\/(obj|img)\/(ad-app-package|ad)\/.+ _ reject
^https?:\/\/.+\.(pglstatp-toutiao|pstatp)\.com\/(obj|img)\/web\.business\.image\/.+ _ reject
^https?:\/\/.+\.(pglstatp-toutiao|pstatp)\.com\/obj\/ad-pattern\/renderer _ reject
^https?:\/\/gurd\.snssdk\.com\/src\/server\/v3\/package _ reject
^https?:\/\/.+\.byteimg.com\/tos-cn-i-1yzifmftcy\/(.+)-jpeg\.jpeg _ reject
^https?:\/\/.+\.pstatp\.com\/obj\/mosaic-legacy\/.+\?from\=ad _ reject
^https?:\/\/.+\.pstatp\.com\/bytecom\/resource\/track_log\/src\/.+ _ reject
^https?:\/\/.+\.snssdk\.com\/video\/play\/1\/toutiao\/.+\/mp4 _ reject
^https?:\/\/.+\.snssdk.com\/api\/ad\/.+ _ reject

[MITM]
hostname = %APPEND% *.pangolin-sdk-toutiao,*.pangolin-sdk-toutiao.*,*.pstatp.com,*.pstatp.com.*,*.pglstatp-toutiao.com.*,*.pglstatp-toutiao.com,gurd.snssdk.com,gurd.snssdk.com.*,*default.ixigua.com,*.byteimg.com,*.douyinpic.com,*.bytegecko.com,*.zijieapi.com,*.ecombdimg.com,*.fqnovel.com
